import type { RankedCandidate, ScanResult } from "../../src/orchestrator/types.ts";

export function fixedScanResult(): ScanResult {
  const candidates: RankedCandidate[] = [
    {
      rank: 1,
      app: {
        store: "apple",
        appId: "com.example.calai",
        market: "br",
        name: "Cal AI: Calorie Tracker",
        developer: "Cal AI Inc.",
        category: "Health & Fitness",
        rank: 3,
        rating: 4.7,
        ratingsCount: 89_432,
        priceUsd: 0,
        iapPresent: true,
        description: "Track your calories with AI photo recognition.",
        screenshotUrls: ["https://example.com/calai-1.png"],
        iconUrl: "https://example.com/calai-icon.png",
        releaseDate: null,
        lastUpdated: null,
        scrapedAt: "2026-04-29T12:00:00.000Z",
      },
      composite: {
        composite: 8.2,
        breakdown: { locGap: 9.0, revenue: 8.5, paywall: 6.5, velocity: null },
        weights: { locGap: 0.4, revenue: 0.4, paywall: 0.2, velocity: 0 },
      },
      textJudge: {
        kind: "text",
        appId: "com.example.calai",
        store: "apple",
        market: "br",
        locGapScore: 9.0,
        reasoning: "English-only listing on a Brazilian top chart, no PIX.",
        signals: {
          hasNativeLanguage: false,
          hasCulturalAdaptation: false,
          hasLocalizedPaywall: false,
          hasLocalPaymentMethod: false,
        },
        confidence: 0.85,
        modelVersion: "claude-sonnet-4-6",
      },
      visionJudge: {
        kind: "vision",
        appId: "com.example.calai",
        store: "apple",
        market: "br",
        culturalFitScore: 7.0,
        reasoning: "US-style food imagery, English captions on every screenshot.",
        signals: {
          screenshotsLocalized: false,
          imagesCulturallyAdapted: false,
          textInLanguage: false,
          screenshotFreshness: "stale",
        },
        screenshotsAnalyzed: 5,
        confidence: 0.75,
        modelVersion: "claude-sonnet-4-6",
      },
    },
    {
      rank: 2,
      app: {
        store: "google",
        appId: "com.example.remini",
        market: "jp",
        name: "Remini",
        developer: "Bending Spoons",
        category: "Photo & Video",
        rank: 12,
        rating: 4.5,
        ratingsCount: 230_000,
        priceUsd: 0,
        iapPresent: true,
        description: "AI photo enhancer.",
        screenshotUrls: [],
        iconUrl: null,
        releaseDate: null,
        lastUpdated: null,
        scrapedAt: "2026-04-29T12:00:00.000Z",
      },
      composite: {
        composite: 6.4,
        breakdown: { locGap: 5.5, revenue: 7.0, paywall: 6.5, velocity: 6.0 },
        weights: { locGap: 0.3, revenue: 0.3, paywall: 0.15, velocity: 0.25 },
      },
      textJudge: {
        kind: "text",
        appId: "com.example.remini",
        store: "google",
        market: "jp",
        locGapScore: 5.5,
        reasoning: "Partial JP localization but paywall stays English.",
        signals: {
          hasNativeLanguage: true,
          hasCulturalAdaptation: false,
          hasLocalizedPaywall: false,
          hasLocalPaymentMethod: false,
        },
        confidence: 0.7,
        modelVersion: "claude-sonnet-4-6",
      },
      visionJudge: null,
    },
  ];
  return {
    runId: "run-2026-04-29T12-00-00",
    generatedAt: "2026-04-29T12:00:00.000Z",
    markets: ["us", "jp", "de", "fr", "br", "es"],
    appsScanned: 280,
    costUsd: 1.23,
    candidates,
    judgeResults: [],
    snapshotResult: { written: 280, skipped: 0, day: "2026-04-29" },
    failedSlices: [],
  };
}
